config/routes.rb
NewTap::Application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  match 'search_user' => 'search#search_user', as: :user_search
  match 'search_clan' => 'search#search_clan', as: :clan_search

  match 'search_user/:user' => 'search#user', as: :search_user
  match 'search_clan/:clan' => 'search#clan', as: :search_clan

  match 'clan_description/:clan_id' => 'search#clan_description', as: :clan_description

  match 'show_owners/:vehicle' => 'vehicles#show_owners', as: :show_owners

  match 'first_battalion' => 'members#first_battalion', as: :first_battalion
  match 'second_battalion' => 'members#second_battalion', as: :second_battalion
  match 'third_battalion' => 'members#third_battalion', as: :third_battalion
  match 'show_battalion_owners/:battalion/:vehicle_name' => 'vehicles#show_battalion_owners', as: :show_battalion_owners

  match 'check_block_status' => 'vehicles#check_block_status', as: :check_block_status

  resources :pages
  resources :members do
    collection do
      get :get_all
    end
    resources :vehicles do
      member do
        get :get_all
      end
    end
  end

  root to: 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    @user = user
    if @user
      send(@user.role.presence)
    else
      send('guest')
    end
  end

  def admin
    can :manage, User
    can :manage, Page
    can :manage, Member
    can :manage, Vehicle
    can :access, :rails_admin
    can :dashboard
  end

  def moderator
    can :access, :rails_admin
    can :dashboard
    can :manage, Member
    can :manage, Vehicle
  end

  def user
    can :read, :all
  end

  def guest
    can :read, Member
  end
end

app/models/member.rb
class Member < ActiveRecord::Base
  include Enumerize
  attr_accessible :name, :rank, :account_id, :last_update, :battalion
  has_many :vehicles, dependent: :destroy

  enumerize :battalion, :in => %w[0 1 2 3], default: '0'
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  include Enumerize
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role, :login

  enumerize :role, :in => %w[admin moderator user], default: 'user'
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  attr_accessible :level, :member_id, :name, :image, :blocked_to
  belongs_to :member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  require 'open-uri'

  respond_to :html

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to '/', :alert => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pages = Page.all
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  load_and_authorize_resource

  respond_to :js, only: :show

  def index
    @members = @members.order("LOWER(name)")
  end

  def get_all
    authorize! :manage, Member
    url = 'http://api.worldoftanks.ru/community/clans/988/api/1.1/?source_token=WG-WoT_Assistant-1.3.2'
    clan_members = JSON.parse(open(url).read)["data"]["members"]
    clan_members.each do |member|
      if Member.where(name: member["account_name"]).empty?
        @member = Member.new(name: member["account_name"], rank: member["role_localised"], account_id: member["account_id"])
        @member.save

      end
    end
    Member.all.each do |member|
      if clan_members.select{|arr| arr["account_name"] == "#{member.name}"}.empty?
        member.destroy
      end
    end
    flash[:notice] = 'Members list updated'
    redirect_to members_path
  end

  def first_battalion
    @members = Member.where(battalion: 1).order("LOWER(name)")
    members_ids = @members.map(&:id)
    @vehicles = Vehicle.where('member_id IN (?)', members_ids).where(level: '10')
  end

  def second_battalion
    @members = Member.where(battalion: 2).order("LOWER(name)")
    members_ids = @members.map(&:id)
    @vehicles = Vehicle.where('member_id IN (?)', members_ids).where(level: '10')
  end

  def third_battalion
    @members = Member.where(battalion: 3).order("LOWER(name)")
    members_ids = @members.map(&:id)
    @vehicles = Vehicle.where('member_id IN (?)', members_ids).where(level: '10')
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search_user

  end

  def search_clan

  end

  def user
    @json_object = get_user(params[:search][:user_name], 99)
  end

  def clan
    @json_object = get_clan(params[:search][:clan_name], 99)
  end

  def clan_description
    clan_url = "http://api.worldoftanks.ru/community/clans/#{params[:clan_id]}/api/1.1/?source_token=WG-WoT_Assistant-1.3.2"
    @clan_json = JSON.parse(open(clan_url).read)
    @vehicles = []
    @clan_json['data']['members'].each_with_index do |member, index|
      member_stat = get_user_stat(member['account_id'])
      @clan_json['data']['members'][index].merge!(member_stat["data"]) unless member_stat["status"] == 'error'
      @vehicles += member_stat['data']["vehicles"].select{|arr| arr['level'] == 10} unless member_stat["status"] == 'error'
    end
  end

  private
    def get_user(user_name, limit)
      url = "http://api.worldoftanks.ru/community/accounts/api/1.1/?source_token=WG-WoT_Assistant-1.3.2&search=#{user_name}&offset=0&limit=#{limit}"
      JSON.parse(open(url).read)
    end

    def get_clan(clan_name, limit)
      url = "http://api.worldoftanks.ru/community/clans/api/1.1/?source_token=WG-WoT_Assistant-1.3.2&search=#{clan_name}&offset=0&limit=#{limit}&order_by=name"
      JSON.parse(open(url).read)
    end

    def get_user_stat(user_id)
      url = "http://api.worldoftanks.ru/community/accounts/#{user_id}/api/1.9/?source_token=WG-WoT_Assistant-1.3.2"
      JSON.parse(open(url).read)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

  respond_to :js

  def get_all
    authorize! :manage, Vehicle
    url = "http://api.worldoftanks.ru/community/accounts/#{params[:id]}/api/1.9/?source_token=WG-WoT_Assistant-1.3.2"
    vehicles = JSON.parse(open(url).read)["data"]["vehicles"]
    vehicles.each do |vehicle|
      if Member.find(params[:member_id]).vehicles.where(name: vehicle["name"]).empty?
        @record = Vehicle.create(name: vehicle["name"], level: vehicle["level"], image: vehicle["image_url"], member_id: params[:member_id])
        if @record.save
          Member.find(params[:member_id]).update_attribute(:last_update, Time.now)
        end
      end
    end
    flash[:notice] = "Vehicles of member #{Member.find(params[:member_id]).name} accepted"
    redirect_to members_path
  end

  def show_owners
    authorize! :manage, Vehicle
    @vehicles = Vehicle.where(name: params[:vehicle])
  end

  def show_battalion_owners
    authorize! :manage, Vehicle
    @members = Member.where(battalion: params[:battalion])
    members_ids = @members.map(&:id)
    @vehicles = Vehicle.where('member_id IN (?)', members_ids).where(level: '10').where(name: params[:vehicle_name])
  end

  def check_block_status
    authorize! :manage, Vehicle
    Vehicle.where('vehicles.blocked_to <(?)', Time.now).update_all(blocked_to: nil)
    flash[:notice] = "Blocked status of vehicles updated"
    redirect_to members_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def sign_in_link
    if current_user.nil?
      link_to 'Sign In', new_user_session_path
    else
      link_to 'Sign Out', destroy_user_session_path, method: :delete
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
  def last_update(date)
    if date < Date.today - 7
      content_tag('td', date.strftime('%d-%m-%Y %H-%M'), class: 'bad')
    else
      content_tag('td', date.strftime('%d-%m-%Y %H-%M'), class: 'good')
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
  def get_image(name)
    image_tag "http://worldoftanks.ru/#{Vehicle.where(name: name).first.image}"
  end

  def get_count(name)
    Vehicle.where(name: name).count
  end
end

app/views/bars/_top_bar.html.slim
.navbar.navbar-inverse
  .navbar-inner
    .container-fluid
      a.btn.btn-navbar data-target=".nav-inverse" data-toggle="inverse"
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.brand href="/"NewTap
      .container-fluid.nav-inverse
        ul.nav
          li.divider-vertical
          li = sign_in_link
          li.divider-vertical
          li = link_to 'Sign up', new_user_registration_path
          li.divider-vertical
          li = link_to 'Members List', members_path
          li.divider-vertical
          li = link_to 'Admin panel', rails_admin_path if can? :access, :rails_admin
          li.divider-vertical
          - if can? :manage, Member
            li.dropdown
              a.dropdown-toggle#drop1 data-toggle="dropdown" href='#'
                | Battalions
                b.caret
              <ul class="dropdown-menu">
                <li><a href="/first_battalion">First Battalion</a></li>
                <li><a href="/second_battalion">Second Battalion</a></li>
                <li><a href="/third_battalion">Third Battalion</a></li>
              </ul>
            li.divider-vertical
            li = link_to 'Check Block Status', check_block_status_path
            li.divider-vertical
        - unless current_user.nil?
          ul.nav.pull-right
            li = link_to "Login as: #{current_user.login}", '#'

app/views/home/index.html.slim
.span12
  .span8.offset2
    h1 Welcome!
  - @pages.each do |page|
    .row-fluid
      .span6.offset2
        h4 = page.title
      .span2
        h6 = page.created_at.strftime("%d %B  %Y")
    .row-luid.pages_content
      .span8.offset2
        = page.content

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "NewTap"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'



  body
    = render 'bars/top_bar'
    .container-fluid
      .row-fluid
        .span10.offset1
          = bootstrap_flash
          = yield
    .footer
      | &copy; Hahander Web-studio 2013
    /!
      Javascripts
      \==================================================
    /! Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/members/_details.html.slim
.span12
  - if @member.vehicles.empty?
    h6 No data to display
  - else
    .row-fluid
      .span6
        h6 10 lvl
        table
          - @member.vehicles.where(level: '10').each do |vehicle|
            tr
              td = get_image(vehicle.name)
              td = vehicle.name
      .span6
        h6 8 lvl
        table
          - @member.vehicles.where(level: '8').each do |vehicle|
            tr
              td = get_image(vehicle.name)
              td = vehicle.name

app/views/members/first_battalion.html.slim
.row
  .span4.offset2
    h2 First Battalion
- if @vehicles.empty?
  .row
    .span4.offset2
      h4 No members found
- else
  .row-fluid
    .span4.offset2
      h4 = "#{@members.count} members total"
      table.table
        thead
          tr
            th Name
            th Rank
            - if can? :manage, Member
              th Last update
              th Actions
        tbody
          - @members.each do |member|
            tr
              td
                = content_tag('span', member.name, class: 'member_details', data: {member_id: member.id})
              td = member.rank
              - if can? :manage, Member
                - if member.last_update.nil?
                  td.bad Never
                - else
                  td.good = member.last_update.strftime('%d-%m-%Y %H-%M')
                td = link_to 'Get Vehicles', get_all_member_vehicle_path(member, member.account_id), class: 'btn btn-primary btn-mini'
    .span4
      h4 Vehicles
      table.table
        thead
          tr
            th
            th Name
            th Count
        tbody
          - @vehicles.map(&:name).uniq.each do |v_name|
            tr
              th = get_image(v_name)
              th
                - if can? :manage, Member
                  = content_tag('span', v_name, class: 'battalion_vehicle_details', data: {vehicle_name: v_name, battalion: 1})
                - else
                  = v_name
              th = @vehicles.where(name: v_name).count
    .custom_modal
      .close X
      .content

app/views/members/index.html.slim
.row
  .span4.offset2
    - if can? :manage, Member
      = link_to 'Update member list', get_all_members_path, class: 'btn btn-primary'

.row-fluid
  .span4.offset2
    h2 Surreal
.row-fluid
  .span4.offset1
    h4 = "#{@members.count} members total"
    table.table
      thead
        tr
          th Name
          th Rank
          - if can? :manage, Member
            th Last update
            th Actions
      tbody
        - @members.each do |member|
          tr
            td
              = content_tag('span', member.name, class: 'member_details', data: {member_id: member.id})
            td = member.rank
            - if can? :manage, Member
              - if member.last_update.nil?
                td.bad Never
              - else
                  = last_update(member.last_update)
              td = link_to 'Get Vehicles', get_all_member_vehicle_path(member, member.account_id), class: 'btn btn-primary btn-mini'
  .span4.offset2
    h4 Vehicles
    table.table
      thead
        tr
          th
          th Name
          th Count
      tbody
        - Vehicle.where(level: '10').order('name').map(&:name).uniq.each do |v_name|
          tr
            th = get_image(v_name)
            th
              - if can? :manage, Member
                = content_tag('span', v_name, class: 'vehicle_details', data: {vehicle_name: v_name})
              - else
                = v_name
            th = get_count(v_name)
  .custom_modal
    .close X
    .content

app/views/members/second_battalion.html.slim
.row
  .span4.offset2
    h2 Second Battalion
- if @vehicles.empty?
  .row
    .span4.offset2
      h4 No members found
- else
  .row-fluid
    .span4.offset2
      h4 = "#{@members.count} members total"
      table.table
        thead
          tr
            th Name
            th Rank
            - if can? :manage, Member
              th Last update
              th Actions
        tbody
          - @members.each do |member|
            tr
              td
                = content_tag('span', member.name, class: 'member_details', data: {member_id: member.id})
              td = member.rank
              - if can? :manage, Member
                - if member.last_update.nil?
                  td.bad Never
                - else
                  td.good = member.last_update.strftime('%d-%m-%Y %H-%M')
                td = link_to 'Get Vehicles', get_all_member_vehicle_path(member, member.account_id), class: 'btn btn-primary btn-mini'
    .span4
      h4 Vehicles
      table.table
        thead
          tr
            th
            th Name
            th Count
        tbody
          - @vehicles.map(&:name).uniq.each do |v_name|
            tr
              th = get_image(v_name)
              th
                - if can? :manage, Member
                  = content_tag('span', v_name, class: 'battalion_vehicle_details', data: {vehicle_name: v_name, battalion: 1})
                - else
                  = v_name
              th = @vehicles.where(name: v_name).count
    .custom_modal
      .close X
      .content

app/views/members/show.js.erb
$('.popover-content').html("<%=j (render 'details') %>");
$('.popover-title').html("<%=j (@member.name) %>")
$('.popover-title').append("<%=j (content_tag('span', 'Close', class: 'close_popover btn btn-mini')) %>")

app/views/members/third_battalion.html.slim
.row
  .span4.offset2
    h2 Third Battalion
- if @vehicles.empty?
  .row
    .span4.offset2
      h4 No members found
- else
  .row-fluid
    .span4.offset2
      h4 = "#{@members.count} members total"
      table.table
        thead
          tr
            th Name
            th Rank
            - if can? :manage, Member
              th Last update
              th Actions
        tbody
          - @members.each do |member|
            tr
              td
                = content_tag('span', member.name, class: 'member_details', data: {member_id: member.id})
              td = member.rank
              - if can? :manage, Member
                - if member.last_update.nil?
                  td.bad Never
                - else
                  td.good = member.last_update.strftime('%d-%m-%Y %H-%M')
                td = link_to 'Get Vehicles', get_all_member_vehicle_path(member, member.account_id), class: 'btn btn-primary btn-mini'
    .span4
      h4 Vehicles
      table.table
        thead
          tr
            th
            th Name
            th Count
        tbody
          - @vehicles.map(&:name).uniq.each do |v_name|
            tr
              th = get_image(v_name)
              th
                - if can? :manage, Member
                  = content_tag('span', v_name, class: 'battalion_vehicle_details', data: {vehicle_name: v_name, battalion: 1})
                - else
                  = v_name
              th = @vehicles.where(name: v_name).count
    .custom_modal
      .close X
      .content

app/views/search/clan.html.slim
- if @json_object["data"]["items"].any?
  h1 = "Find #{@json_object["data"]["items"].count} clans"
  table
    - @json_object["data"]["items"].each do |clan|
      tr
        td = image_tag clan["clan_emblem_url"]
        td = "#{clan["name"]}[#{clan["abbreviation"]}]"
        td = link_to "Show more", clan_description_path(clan["id"])
- else
  h1 Clan not found

app/views/search/clan_description.html.slim
h4 = "#{@clan_json['data']['name']}[#{@clan_json['data']['abbreviation']}]"
.small-6.columns
  h6 = "#{@clan_json['data']['members_count']} members"
  table
    - @clan_json['data']['members'].each do |member|
      tr
        td = member['account_name']
        td = member['role_localised']
        - if member["ratings"].nil?
          td Not active
        - else
          - if member['ratings']['battle_avg_performance']['value'].to_i > 52
            td.good = "#{member['ratings']['battle_avg_performance']['value']}%"
          - else
            td.bad = "#{member['ratings']['battle_avg_performance']['value']}%"
.small-6.columns.end
  h6 Vehicles count
  table
    - @vehicles.map{|s| s['name']}.uniq.each do |name|
      tr
        td = name
        td = image_tag "#{APP_CONFIG["development"][:wg_site]}/#{@vehicles.select{|a| a['name'] == name}.first['image_url']}"
        td = @vehicles.select{|a| a["name"] == name}.count

app/views/search/search_clan.html.slim
h1 Search clan
= simple_form_for :search, url: search_clan_path(:clan_name) do |f|
  = f.input :clan_name
  = f.submit

app/views/search/search_user.html.slim
h1 Search user
= simple_form_for :search, url: search_user_path(:user_name) do |f|
  = f.input :user_name
  = f.submit

app/views/search/user.html.slim
table
  - if @json_object["data"]["items"].any?
    h4 = "Find #{@json_object["data"]["items"].count} users"
    - @json_object["data"]["items"].each do |user|
      tr
        td
          h6 = user["name"]
        td
          = user["clan"].nil? ? 'no clan' : user["clan"]["tag"]
        td = link_to "View on wargaming website", "#{APP_CONFIG["development"][:wg_site]}/#{user["url"]}", target: '_blank'
  - else
    h1 User not found

app/views/vehicles/_vehicles.html.slim
table.table
  thead
    tr
      th Owner
      th Blocked to
  tbody
    - @vehicles.each do |vehicle|
      tr
        td = vehicle.member.name
        - if vehicle.blocked_to.nil?
          td.good Active
        - else
          td.bad = vehicle.blocked_to.strftime('%d-%m-%Y %H-%M')

app/views/vehicles/show_battalion_owners.js.erb
$('.popover-content').html("<%=j (render 'vehicles') %>");
$('.popover-title').html("<%=j (@vehicles.first.name) %>")
$('.popover-title').append("<%=j (content_tag('span', 'Close', class: 'close_popover btn btn-mini')) %>")

app/views/vehicles/show_owners.js.erb
$('.popover-content').html("<%=j (render 'vehicles') %>");
$('.popover-title').html("<%=j (@vehicles.first.name) %>")
$('.popover-title').append("<%=j (content_tag('span', 'Close', class: 'close_popover btn btn-mini')) %>")